name: WorldTV – menu M3U / Xtream / STB (Gradle 8.7 + AGP 8.5.2)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Verrouille Gradle 8.7 (évite Gradle 9)
      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-read-only: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate Android project (SDK 34, Media3)
        run: |
          set -e
          mkdir -p app/src/main/java/com/worldtv
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values

          # settings.gradle (repos modernes)
          cat > settings.gradle <<'EOF'
          pluginManagement {
            repositories { gradlePluginPortal(); google(); mavenCentral() }
          }
          dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
            repositories { google(); mavenCentral() }
          }
          rootProject.name = "worldtv"
          include(":app")
          EOF

          # build.gradle (root)
          cat > build.gradle <<'EOF'
          // plugins et repos gérés dans settings.gradle et app/build.gradle
          EOF

          # app/build.gradle (AGP 8.5.2 + Media3 1.4.1)
          cat > app/build.gradle <<'EOF'
          plugins {
            id 'com.android.application' version '8.5.2'
          }

          android {
            namespace "com.worldtv"
            compileSdk 34
            defaultConfig {
              applicationId "com.worldtv"
              minSdk 21
              targetSdk 34
              versionCode 1
              versionName "1.0"
            }
            buildTypes { release { minifyEnabled false } }
            compileOptions {
              sourceCompatibility JavaVersion.VERSION_17
              targetCompatibility JavaVersion.VERSION_17
            }
          }

          dependencies {
            implementation 'androidx.appcompat:appcompat:1.6.1'
            implementation 'com.google.android.material:material:1.9.0'
            implementation 'androidx.media3:media3-exoplayer:1.4.1'
            implementation 'androidx.media3:media3-exoplayer-hls:1.4.1'
            implementation 'androidx.media3:media3-ui:1.4.1'
          }
          EOF

          # Manifest : MainActivity = menu (launcher/exported), le reste sans intent-filter
          cat > app/src/main/AndroidManifest.xml <<'EOF'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
            <application
                android:label="World TV"
                android:theme="@style/Theme.Material3.DayNight.NoActionBar">

              <activity
                  android:name=".MainActivity"
                  android:exported="true">
                <intent-filter>
                  <action android:name="android.intent.action.MAIN"/>
                  <category android:name="android.intent.category.LAUNCHER"/>
                </intent-filter>
              </activity>

              <activity android:name=".M3UInputActivity" android:exported="false"/>
              <activity android:name=".XtreamInputActivity" android:exported="false"/>
              <activity android:name=".StbInputActivity" android:exported="false"/>
              <activity android:name=".PlayerActivity" android:exported="false"/>

            </application>
          </manifest>
          EOF

          # ---------- Layouts ----------
          # Menu 3 choix
          cat > app/src/main/res/layout/activity_main.xml <<'EOF'
          <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:padding="24dp"
              android:gravity="center"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
              <Button
                  android:id="@+id/btn_m3u"
                  android:text="M3U / M3U8"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"/>
              <Button
                  android:id="@+id/btn_xtream"
                  android:text="Xtream Codes"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  android:layout_marginTop="16dp"/>
              <Button
                  android:id="@+id/btn_stb"
                  android:text="STB (MAG/Stalker)"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  android:layout_marginTop="16dp"/>
          </LinearLayout>
          EOF

          # M3U : saisie URL
          cat > app/src/main/res/layout/activity_m3u_input.xml <<'EOF'
          <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:padding="16dp"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
              <EditText
                  android:id="@+id/url_input"
                  android:hint="https://.../playlist.m3u8 (ou .m3u)"
                  android:inputType="textUri"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content" />
              <Button
                  android:id="@+id/btn_play_m3u"
                  android:text="Lire"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  android:layout_marginTop="16dp" />
          </LinearLayout>
          EOF

          # Xtream : host/user/pass (placeholder)
          cat > app/src/main/res/layout/activity_xtream_input.xml <<'EOF'
          <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:padding="16dp"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
              <EditText
                  android:id="@+id/xt_host"
                  android:hint="http://host:port"
                  android:inputType="textUri"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"/>
              <EditText
                  android:id="@+id/xt_user"
                  android:hint="username"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"/>
              <EditText
                  android:id="@+id/xt_pass"
                  android:hint="password"
                  android:inputType="textPassword"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"/>
              <Button
                  android:id="@+id/xt_save"
                  android:text="Enregistrer (à brancher)"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  android:layout_marginTop="16dp"/>
          </LinearLayout>
          EOF

          # STB : portal + MAC (placeholder)
          cat > app/src/main/res/layout/activity_stb_input.xml <<'EOF'
          <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:padding="16dp"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
              <EditText
                  android:id="@+id/stb_portal"
                  android:hint="http://host/stalker_portal/"
                  android:inputType="textUri"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"/>
              <EditText
                  android:id="@+id/stb_mac"
                  android:hint="MAC (ex: 00:1A:79:xx:xx:xx)"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"/>
              <Button
                  android:id="@+id/stb_save"
                  android:text="Enregistrer (à brancher)"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  android:layout_marginTop="16dp"/>
          </LinearLayout>
          EOF

          # Player
          cat > app/src/main/res/layout/activity_player.xml <<'EOF'
          <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent">
              <androidx.media3.ui.PlayerView
                  android:id="@+id/player_view"
                  android:layout_width="match_parent"
                  android:layout_height="match_parent"/>
          </FrameLayout>
          EOF

          # strings.xml
          cat > app/src/main/res/values/strings.xml <<'EOF'
          <resources><string name="app_name">World TV</string></resources>
          EOF

          # ---------- Java ----------
          cat > app/src/main/java/com/worldtv/MainActivity.java <<'EOF'
          package com.worldtv;

          import android.app.Activity;
          import android.content.Intent;
          import android.os.Bundle;

          public class MainActivity extends Activity {
              @Override protected void onCreate(Bundle b) {
                  super.onCreate(b);
                  setContentView(R.layout.activity_main);
                  findViewById(R.id.btn_m3u).setOnClickListener(v ->
                      startActivity(new Intent(this, M3UInputActivity.class)));
                  findViewById(R.id.btn_xtream).setOnClickListener(v ->
                      startActivity(new Intent(this, XtreamInputActivity.class)));
                  findViewById(R.id.btn_stb).setOnClickListener(v ->
                      startActivity(new Intent(this, StbInputActivity.class)));
              }
          }
          EOF

          cat > app/src/main/java/com/worldtv/M3UInputActivity.java <<'EOF'
          package com.worldtv;

          import android.app.Activity;
          import android.content.Intent;
          import android.os.Bundle;
          import android.widget.Button;
          import android.widget.EditText;

          public class M3UInputActivity extends Activity {
              @Override protected void onCreate(Bundle b) {
                  super.onCreate(b);
                  setContentView(R.layout.activity_m3u_input);
                  EditText url = findViewById(R.id.url_input);
                  Button play = findViewById(R.id.btn_play_m3u);
                  play.setOnClickListener(v -> {
                      String u = url.getText().toString().trim();
                      Intent i = new Intent(this, PlayerActivity.class);
                      i.putExtra("url", u);
                      startActivity(i);
                  });
              }
          }
          EOF

          cat > app/src/main/java/com/worldtv/XtreamInputActivity.java <<'EOF'
          package com.worldtv;

          import android.app.Activity;
          import android.os.Bundle;
          import android.widget.Button;
          import android.widget.EditText;
          import android.widget.Toast;

          public class XtreamInputActivity extends Activity {
              @Override protected void onCreate(Bundle b) {
                  super.onCreate(b);
                  setContentView(R.layout.activity_xtream_input);
                  EditText host = findViewById(R.id.xt_host);
                  EditText user = findViewById(R.id.xt_user);
                  EditText pass = findViewById(R.id.xt_pass);
                  Button save = findViewById(R.id.xt_save);
                  save.setOnClickListener(v -> {
                      // TODO: stocker et brancher l'API Xtream
                      Toast.makeText(this,"Xtream enregistré (à brancher)",Toast.LENGTH_SHORT).show();
                  });
              }
          }
          EOF

          cat > app/src/main/java/com/worldtv/StbInputActivity.java <<'EOF'
          package com.worldtv;

          import android.app.Activity;
          import android.os.Bundle;
          import android.widget.Button;
          import android.widget.EditText;
          import android.widget.Toast;

          public class StbInputActivity extends Activity {
              @Override protected void onCreate(Bundle b) {
                  super.onCreate(b);
                  setContentView(R.layout.activity_stb_input);
                  EditText portal = findViewById(R.id.stb_portal);
                  EditText mac = findViewById(R.id.stb_mac);
                  Button save = findViewById(R.id.stb_save);
                  save.setOnClickListener(v -> {
                      // TODO: brancher handshake MAG/Stalker
                      Toast.makeText(this,"STB enregistré (à brancher)",Toast.LENGTH_SHORT).show();
                  });
              }
          }
          EOF

          cat > app/src/main/java/com/worldtv/PlayerActivity.java <<'EOF'
          package com.worldtv;

          import android.net.Uri;
          import android.os.Bundle;
          import androidx.appcompat.app.AppCompatActivity;
          import androidx.media3.common.MediaItem;
          import androidx.media3.exoplayer.ExoPlayer;
          import androidx.media3.ui.PlayerView;

          public class PlayerActivity extends AppCompatActivity {
              private ExoPlayer player;
              @Override protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  setContentView(R.layout.activity_player);
                  String url = getIntent().getStringExtra("url");
                  if (url == null || url.isEmpty()) {
                      url = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8";
                  }
                  player = new ExoPlayer.Builder(this).build();
                  PlayerView pv = findViewById(R.id.player_view);
                  pv.setPlayer(player);
                  player.setMediaItem(MediaItem.fromUri(Uri.parse(url)));
                  player.prepare(); player.play();
              }
              @Override protected void onDestroy() {
                  super.onDestroy();
                  if (player != null) { player.release(); player = null; }
              }
          }
          EOF

      - name: Build Debug APK
        run: gradle --no-build-cache assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WorldTV-debug-apk
          path: app/build/outputs/apk/debug/*.apk
