name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # Utilise le wrapper s'il existe, sinon le gradle système
      - name: Build Debug APK
        run: |
          if [ -x "./gradlew" ]; then
            chmod +x gradlew
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: WorldTV-debug-apk
          path: app/build/outputs/apk/debug/*.apk
